### PR TITLE
Accept jQuery, Angular & HTML elements - fix #94

### LINKED ISSUE #94: jQuery example doesn't work
Click on jQuery HTML example on https://limonte.github.io/sweetalert2/

You'll get [object Object]

It would be really useful to be able to provide an HTML element, not just a string of code

### PR DESCRIPTION
**Pull request by jbdemonte**

### CODE REVIEW

File: src/sweetalert2.js [hunk 1]
```diff
@@ -640,7 +640,18 @@
 
     // Content
     if (params.text || params.html) {
-      $content.innerHTML = params.html || ('<p>' + escapeHtml(params.text.split('\n').join('<br>')) + '</p>');
+      if (typeof params.html === 'object') {
+        $content.innerHTML = '';
+        if (0 in params.html) {
```
Comment (limonte) [inline src/sweetalert2.js]: can you please add the comment to this line, this condition isn't quite obvious.

Comment (limonte) [inline src/sweetalert2.js]: no need actually, I got it - nice trick! btw Array.isArray doesn't work as expected here

Comment (jbdemonte) [inline src/sweetalert2.js]: Thanks,
I didn't use Array.isArray because I didn't know what browser compatibility do sweetalert provide
